services:
  light:
    image: kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cyclosm
    deploy:
      resources:
        reservations:
          cpus: '10'
          memory: 16G
    depends_on:
      - db
    ports:
      - "127.0.0.1:6789:6789"
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - THEME=light
      - PORT=6789
  dark:
    image: kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/cyclosm
    deploy:
      resources:
        reservations:
          cpus: '10'
          memory: 16G
    depends_on:
      - db
    ports:
      - "127.0.0.1:6790:6790"
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - THEME=dark
      - PORT=6790
  db:
    image: world-bike-map-tile-server-db
    shm_size: 2gb
    cpus: "8"
    mem_reservation: "6G"
    build:
      context: .
      dockerfile: Dockerfile.db
    deploy:
      resources:
        reservations:
          cpus: '8'
          memory: 6G
    ports:
      - "5432:5432"
    environment:
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - THREADS=8
      - OSM2PGSQL_EXTRA_ARGS=-C 8192
      - PGPASSWORD=postgres
    volumes:
      - osm-data:/var/lib/postgresql/data
  import:
    image: world-bike-map-tile-server-import
    shm_size: 2gb
    cpus: "8"
    mem_reservation: "6G"
    build:
      context: .
      dockerfile: Dockerfile.import
    deploy:
      resources:
        reservations:
          cpus: '8'
          memory: 6G
    volumes:
      - .:/cyclosm
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - CACHE=8000
      - THREADS=10
      - OSM2PGSQL_DATAFILE
  contours:
    image: world-bike-map-tile-server-contours
    shm_size: 2gb
    cpus: "8"
    mem_reservation: "6G"
    build:
      context: .
      dockerfile: Dockerfile.contours
    deploy:
      resources:
        reservations:
          cpus: '8'
          memory: 6G
    volumes:
      - .:/cyclosm
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - CACHE=8000
      - THREADS=10
      - OSM2PGSQL_DATAFILE
volumes:
  osm-data:
    external: true
